<a href="https://colab.research.google.com/github/wingated/cs474_labs_f2019/blob/master/DL_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 3: Intro to CNNs and DNNs

## Objectives

* Build and train a deep conv net
* Explore and implement various initialization techniques
* Implement a parameterized module in Pytorch
* Use a principled loss function

## Video Tutorial
[https://youtu.be/3TAuTcx-VCc](https://youtu.be/3TAuTcx-VCc)

## Deliverable
For this lab, you will submit an ipython notebook via learningsuite.
This is where you build your first deep neural network!

For this lab, we'll be combining several different concepts that we've covered during class,
including new layer types, initialization strategies, and an understanding of convolutions.

## Grading Standards:
* 20% Part 0: Successfully followed lab video and typed in code
* 20% Part 1: Re-implement Conv2D and CrossEntropy loss function
* 20% Part 2: Implement different initialization strategies
* 10% Part 3: Print parameters, plot train/test accuracy
* 10% Reach 85% validation accuracy from parts 1-3
* 10% Part 4: Convolution parameters quiz
* 10% Tidy and legible figures, including labeled axes where appropriate
___

### Part 0
Watch and follow video tutorial:

[https://youtu.be/3TAuTcx-VCc](https://youtu.be/3TAuTcx-VCc)

**TODO:**

* Watch tutorial

**DONE:**

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
from torchvision import transforms, utils, datasets
from tqdm import tqdm
from torch.nn.parameter import Parameter
import pdb

assert torch.backends.mps.is_available(), "You need to request a GPU from Runtime > Change Runtime"

In [5]:
from torch.nn.parameter import Parameter
import pdb

In [10]:
# Use the dataset class you created in lab2
class FashionMNISTProcessedDataset(Dataset):
    def __init__(self, root, train=True):
        self.data = datasets.FashionMNIST(root, train=train, transform=transforms.ToTensor(), download=True)
    
    def __getitem__(self, i):
        x, y = self.data[i]
        return x, y

    def __len__(self):
        return(len(self.data))

___

### Part 1
Re-implement a Conv2D module with parameters and a CrossEntropy loss function.

**TODO:**

* CrossEntropyLoss 
* Conv2D

**DONE:**

___

### Part 2
Implement a few initialization strategies which can include Xe initialization
(sometimes called Xavier), Orthogonal initialization, and uniform random.
You can specify which strategy you want to use with a parameter. 



Helpful links include:
*  [Orthogonal Initialization](https://hjweide.github.io/orthogonal-initialization-in-convolutional-layers) (or the original paper: http://arxiv.org/abs/1312.6120)
*  http://andyljones.tumblr.com/post/110998971763/an-explanation-of-xavier-initialization

**TODO:**
* Parameterize custom Conv2D for different initilization strategies
* Xe
* Orthogonal
* Uniform

**DONE:**



In [87]:
a = torch.rand(10,10,2)

In [89]:
a.dtype

torch.float32

In [168]:
a = torch.from_numpy(np.random.randn(3,10).astype(np.float32))
b = torch.exp(a)
i = torch.tensor([7,8,9])
r = torch.arange(b.size(0))
c = i
c = c.to("cpu")
b[r,c]

tensor([0.2443, 3.4256, 2.6980])

In [169]:
r, c

(tensor([0, 1, 2]), tensor([7, 8, 9]))

In [170]:
b

tensor([[ 4.8204,  0.7309,  0.2606,  1.1834,  2.5690,  5.5925,  0.7306,  0.2443,
          1.9174,  0.8329],
        [ 0.9049,  1.3221,  0.7915,  0.8517,  0.2739,  1.4884,  1.7747,  0.4180,
          3.4256,  0.7514],
        [ 3.5522,  1.9014,  0.5553,  0.6039,  1.0626,  0.6773, 11.4739,  0.4043,
          0.7381,  2.6980]])

When you pass in a tensor or a list of indices in the form $\verb+b[r,c]+$ where $r$ and $c$ are tensors of indices, then it will index with $r$ as the rows you want to look at, and $c$ as the columns you want to look at and choose the corresponding elements. So, in the example above, if we have $r$ and $c$ as defined, the elements of the $b$ matrix we will be looking at are $(0,7), (1,8), \text{ and }(2,9)$.

In [171]:
torch.softmax(y_pred, 1) # This is turning the tensor of numbers into probabilities

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 4.3794e-37, 1.5757e-36, 1.1602e-15,
         0.0000e+00, 1.0000e+00, 2.3102e-28, 3.6951e-14],
        [3.1730e-13, 0.0000e+00, 9.3294e-12, 3.8734e-13, 1.3607e-17, 1.0478e-03,
         5.5936e-13, 4.5145e-13, 9.9895e-01, 1.9576e-12],
        [0.0000e+00, 0.0000e+00, 3.5145e-28, 0.0000e+00, 9.5574e-27, 4.0868e-22,
         0.0000e+00, 2.6799e-16, 2.0034e-34, 1.0000e+00],
        [1.8896e-20, 1.0000e+00, 0.0000e+00, 7.7824e-13, 6.9604e-29, 0.0000e+00,
         1.5235e-22, 1.8787e-38, 0.0000e+00, 7.9691e-28],
        [2.2058e-35, 8.2083e-22, 2.4448e-11, 7.4304e-27, 1.0000e+00, 0.0000e+00,
         2.5495e-10, 0.0000e+00, 8.8845e-16, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.5157e-16,
         0.0000e+00, 3.3108e-23, 8.8133e-27, 1.0000e+00],
        [1.0000e+00, 7.5837e-38, 6.0599e-14, 5.5334e-20, 2.9965e-24, 0.0000e+00,
         1.6991e-11, 0.0000e+00, 1.0855e-37, 6.3667e-32],
        [9.9998e-01, 3.8310

In [184]:
torch.softmax(y_pred,1).size()

torch.Size([42, 10])

In [177]:
class_pred = torch.softmax(y_pred,1).argmax(1) # This tells us the most likely class the network thinks it should be.
class_pred

tensor([7, 8, 9, 1, 4, 9, 0, 0, 9, 9, 7, 4, 5, 1, 2, 9, 4, 4, 4, 5, 5, 5, 9, 7,
        4, 8, 3, 2, 4, 1, 0, 4, 6, 0, 5, 5, 1, 0, 9, 1, 8, 2], device='mps:0')

In [176]:
y_truth

tensor([7, 8, 9, 1, 4, 9, 0, 0, 5, 9, 5, 2, 7, 1, 2, 9, 4, 4, 4, 5, 5, 5, 9, 7,
        4, 8, 3, 2, 4, 6, 0, 3, 0, 6, 5, 5, 3, 0, 9, 1, 6, 0], device='mps:0')

In [181]:
(class_pred == y_truth).float().mean() # Want this number to be as close to 1 as possible

tensor(0.7381, device='mps:0')

In [154]:
class CrossEntropyLoss(nn.Module):
  def __init__(self, weight=None, size_average=None, ignore_index=- 100, reduce=None, reduction='mean', label_smoothing=0.0):
    super(CrossEntropyLoss, self).__init__()

  def forward(self, y_pred, y_truth):
    

class Conv2d(nn.Module):
  def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None, init="unif"):
    self.__dict__.update(locals()) # keys are arguments we pass in! that way we can just use a dot for any of the argument inputs when we want to reference them, ie self.in_channels
    super(Conv2d, self).__init__()

    self.weight = Parameter(torch.Tensor(out_channels,
                               in_channels, *kernel_size))
    self.bias = Parameter(torch.Tensor(out_channels))

    self.bias.data.uniform_(0,0)
    if init == "unif":
      self.weight.data.uniform_(-1,1)
    if init == "Xe":
      var = 1 / (in_channels * kernel_size[0] * kernel_size[1])
      d = ((12*var)**(.5))/2
      d = 6./(1/var + out_channels)
      self.weight.data.uniform_(-d,d)
    if init == "orthogonal":
      X = np.random.random((out_channels,in_channels*kernel_size[0]*kernel_size[1]))
      U, _, Vt = np.linalg.svd(X, full_matrices=False)
      self.weight.data = torch.from_numpy(Vt.reshape((out_channels,in_channels,kernel_size[0],kernel_size[1])).astype(np.float32))

    self.weight.data = self.weight.data.to("mps")
    self.bias.data = self.bias.data.to("mps")

  def forward(self, x):
    return F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)

  # def extra_repr(self) -> str:
  #   return super().extra_repr()

torch.Size([30, 30])

Numpy will produce float64 by default, but we need float32, so to get around this, do something like this:
\begin{align*}
    \verb+torch.from_numpy(np.random.rand(10,10).astype(np.float32))+
\end{align*}
and this will make sure the datatypes are all the same.

In [155]:
class ConvNetwork(nn.Module):
  def __init__(self, dataset, init):
    super(ConvNetwork, self).__init__()
    x, y = dataset[0]
    c, h, w = x.size()
    print(c, h, w)
    output = 10

    self.net = nn.Sequential(
      Conv2d(c, 10, (3,3), padding=(1,1), init=init),
      Conv2d(10, output, (28,28), padding=(0,0), init=init) # 28 x 28 indicates the image size
    )

  def forward(self, x):
    return self.net(x).squeeze(2).squeeze(2)

In [153]:
# Initialize device 
device = "mps"
# Initialize Datasets
train_dataset = FashionMNISTProcessedDataset("/tmp/fashionmnist", train=True)
val_dataset = FashionMNISTProcessedDataset("tmp/fashionmnist",train=False)
# Initialize DataLoaders
train_loader = DataLoader(train_dataset, batch_size=42, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=42)
# Initialize Model
model = ConvNetwork(train_dataset)
model = model.to(device)
# Initialize Objective and Optimizer and other parameters
objective = nn.CrossEntropyLoss() #TODO: create Cross entropy loss
optimizer = optim.Adam(model.parameters(), lr=1e-4)
# Initialize empty train and validation loss lists
train_loss = []
val_loss = []
# Number of epochs to run through
num_epochs = 100

1 28 28


In [135]:
# model.net[0].weight.data.uniform_(-1,1)
# model.net[0].weight.data

# o, i, k1, k2 = model.net[0].weight.size()
# W = np.random.randn(*model.net[0].weight.data.size())

# model.net[0].weight.data = torch.from_numpy(W)

In [151]:
a,b,c,d = *model.net[0].weight.data.size()

SyntaxError: can't use starred expression here (2830154579.py, line 1)

In [136]:
# Run your training and validation loop and collect stats
loop = tqdm(total=len(train_loader) * num_epochs, position=0)
for epoch in range(num_epochs):
    batch = 0
    for x, y_truth in train_loader:
        x, y_truth = x.to(device), y_truth.to(device)

        optimizer.zero_grad()

        y_pred = model(x)
        loss = objective(y_pred, y_truth)

        if epoch % 2 == 0 and batch == 0:
            val_loss_list = []
            train_loss.append(loss.item())
            for val_x, val_y_truth in val_loader:
                val_x, val_y_truth = val_x.to(device), val_y_truth.to(device)
                val_y_pred = model(val_x)
                val_loss_list.append(objective(val_y_pred, val_y_truth).item())
            val_loss.append(np.mean(val_loss_list))
        
        loop.set_description("epoch no.:" + str(epoch) + " batch no.:" + str(batch) + " loss:" + str(loss.item()) + " val_loss:" + str(val_loss[-1]))

        loss.backward()
        optimizer.step()

        batch += 1

loop.close()


  0%|          | 0/142900 [02:16<?, ?it/s]
epoch no.:2 batch no.:428 loss:8.282930374145508 val_loss:4.594259302735828:   0%|          | 0/142900 [00:30<?, ?it/s]  

KeyboardInterrupt: 


___

### Part 3
Print the number of parameters in your network and plot accuracy of your training and validation 
set over time. You should experiment with some deep networks and see if you can get a network 
with close to 1,000,000 parameters.

Once you've experimented with multiple network setups and the different initialization strategies, plot the best-performing experiment here. You should be able to exceed 85% accuracy on the validation set.

**TODO:**
* Experiment with Deep Networks
* Plot accuracy of training and validation set over time
* Print out number of parameters in the model 
* Plot experiment results with 85% or better validation accuracy

**DONE:**


In [3]:

# Go back up and try a few different networks and initialization strategies
# Plot loss if you want
# Plot accuracy



In [2]:
# Compute and print the number of parameters in the model


___

### Part 4
Learn about how convolution layers affect the shape of outputs, and answer the following quiz questions. Include these in a new markdown cell in your jupyter notebook.


*Using a Kernel size of 3×3 what should the settings of your 2d convolution be that results in the following mappings (first answer given to you)*

* (c=3, h=10, w=10) ⇒ (c=10, h=8, w=8) : (out_channels=10, kernel_size=(3, 3), padding=(0, 0))
* (c=3, h=10, w=10) ⇒ (c=22, h=10, w=10) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=65, h=12, w=12) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=7, h=20, w=20) : **Your answer in bold here**

*Using a Kernel size of 5×5:*)

* (c=3, h=10, w=10) ⇒ (c=10, h=8, w=8) : (out_channels=10, kernel_size=(5, 5), padding=(1, 1))
* (c=3, h=10, w=10) ⇒ (c=100, h=10, w=10) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=23, h=12, w=12) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=5, h=24, w=24) : **Your answer in bold here**

*Using Kernel size of 5×3:*

* (c=3, h=10, w=10) ⇒ (c=10, h=8, w=8) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=100, h=10, w=10) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=23, h=12, w=12) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=5, h=24, w=24) : **Your answer in bold here**

*Determine the kernel that requires the smallest padding size to make the following mappings possible:*

* (c=3, h=10, w=10) ⇒ (c=10, h=9, w=7) : **Your answer in bold here**
* (c=3, h=10, w=10) ⇒ (c=22, h=10, w=10) : **Your answer in bold here**

**TODO:**

* Answer all the questions above 

**DONE:**


In [1]:
# Write some test code for checking the answers for these problems (example shown in the video)
